### PR TITLE
Auxiliary tags must come after physvol

### PR DESCRIPTION
**Pull request by wdconinc**

### CODE REVIEW

**Comment by rahmans1** [comment]
@wdconinc Is this something that causes problem in parsing or just creates a lot of warnings? When I ran the simulation, I didn't see something that stood out.

**Comment by wdconinc** [comment]
Just warnings.

**Comment by wdconinc** [comment]
By default the warnings are suppressed (since there are many due to undefined G4_ materials). I am looking at them periodically, though.

**Comment by rahmans1** [comment]
I see. It should be ok to merge. Doesn't matter either way.

**Pull request merged**
